<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>BoldKey Login Page</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-05-24T14:21:13</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>4d1bacb6-7212-40e5-ad70-e902b5e284d6</testSuiteGuid>
   <testCaseLink>
      <guid>5eec735e-482d-4a53-8e83-c3c3bd38b0a2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Bold Key Login Page/Positive Case/Login Success - Button</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5610cab0-ed51-4bfa-95bb-7144c34fed2f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40e69205-a677-49f2-8cd6-dbb80fb9e490</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c34298ae-bb55-4def-9835-76501aaa776d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Bold Key Login Page/Negative Case/Login Fail - Button 1</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>eede60cf-aea9-4075-84ba-c74eb2ffeb6d</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Login Page/Login Test Data</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>eede60cf-aea9-4075-84ba-c74eb2ffeb6d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Username</value>
         <variableId>58932289-d5a0-4468-a173-175c2a1d1582</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>eede60cf-aea9-4075-84ba-c74eb2ffeb6d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>24fcc19c-127e-4f2a-8bde-bb74e4fefcb8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f945ff99-d69f-4368-b507-995789b83745</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>332488b2-8b68-48ff-b3f9-247056cd5034</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>be1d1e19-eb7b-47d2-87c9-b514553dd3ac</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>eede60cf-aea9-4075-84ba-c74eb2ffeb6d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Message</value>
         <variableId>29c192aa-ad45-4756-901d-7f68ee1b7bb3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c1ab6861-3fff-4cad-932c-b1c89899e0e8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8aa7d482-6627-451e-9bca-f047d037806a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f17f79b5-bb09-42f9-ba22-b9f928ee1f20</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>118648af-9458-48fa-8e5a-e35b767bf48c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Bold Key Login Page/Close Browser</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
