<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Activity Module - Add one template</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-08-14T18:33:08</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>ba868e68-e080-4631-9660-0987fc07e6c8</testSuiteGuid>
   <testCaseLink>
      <guid>4a3ae46d-e9f3-4efe-81d1-425cd0709d7c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Boldkey Activity Module/Add Activity Page/Add new activity - Select consent</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae11c132-13d5-4942-80c8-022dc6d7fde6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e48d8d4a-1ab0-4eed-a57a-194fdca68961</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bbed0fcd-6db9-4fa4-8323-ad2890e159a8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c7438130-1f08-484f-b561-c799eb5a2b49</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Boldkey Activity Module/Add Template Page/Add new template - One</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6d985080-3d08-4959-80dc-e2bd2dc41ca7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>27c5c0d3-d415-4963-a4ff-530ce883ad87</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e092377b-693d-47e0-b1f0-718052282b17</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4e8fed6a-72a5-4113-b5c8-b636f4a440da</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5e5949ca-8819-460a-ab01-a652369b7084</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fe5596c2-f1f6-4516-b101-c7b00d67059a</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
