<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>username_link</name>
   <tag></tag>
   <elementGuidId>5298a7a3-f4cc-4bd7-9b60-08f618cfafa8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;LayoutController&quot;)/div[@id=&quot;wrapper&quot;]/div[@class=&quot;topbar&quot;]/div[@class=&quot;navbar navbar-default&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;navbar-collapse2&quot;]/ul[@class=&quot;nav navbar-nav navbar-right top-navbar&quot;]/li[@class=&quot;dropdown topbar-profile&quot;]/a[@class=&quot;dropdown-toggle ng-binding&quot;][count(. | //a[@href = '#' and @class = 'dropdown-toggle ng-binding' and @data-toggle = 'dropdown']) = count(//a[@href = '#' and @class = 'dropdown-toggle ng-binding' and @data-toggle = 'dropdown'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-toggle ng-binding</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>cwpreflat</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LayoutController&quot;)/div[@id=&quot;wrapper&quot;]/div[@class=&quot;topbar&quot;]/div[@class=&quot;navbar navbar-default&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;navbar-collapse2&quot;]/ul[@class=&quot;nav navbar-nav navbar-right top-navbar&quot;]/li[@class=&quot;dropdown topbar-profile&quot;]/a[@class=&quot;dropdown-toggle ng-binding&quot;]</value>
   </webElementProperties>
</WebElementEntity>
